package: d2u_machinery
version: '1.1.3'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_machinery

page:
    title: 'translate:d2u_machinery_meta_title'
    perm: d2u_machinery[]
    icon: rex-icon rex-icon-module
    subpages:
        machine: { title: 'translate:d2u_machinery_meta_machines', icon: rex-icon rex-icon-module }
        category: { title: 'translate:d2u_machinery_meta_categories', icon: rex-icon rex-icon-open-category }
        settings: { title: 'translate:d2u_machinery_meta_settings', icon: rex-icon rex-icon-system, perm: d2u_machinery[settings] }
        setup: { title: 'translate:d2u_machinery_meta_setup', icon: rex-icon rex-icon-install, perm: d2u_machinery[settings] }

requires:
    redaxo: '>=5.3.0'
    php:
        version: '>=7.0'
    packages:
        d2u_helper: '>=1.2.4'
        media_manager: '>=2.2'
        tinymce4: '>=0.10'
        sprog: '>=1.0.0'
        url: '>=1.0.0beta5'
        yform: '>=2.0'
        yrewrite: '>=2.0.1'