package: d2u_machinery
version: '1.0.0'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_machinery

page:
    title: 'translate:d2u_machinery_meta_title'
    perm: d2u_machinery[]
    icon: rex-icon rex-icon-module
    subpages:
        machine: { title: 'translate:d2u_machinery_meta_machines', icon: rex-icon rex-icon-module }
        category: { title: 'translate:d2u_machinery_meta_categories', icon: rex-icon rex-icon-open-category }
        settings: { title: 'translate:d2u_machinery_meta_settings', icon: rex-icon rex-icon-system, perm: d2u_machinery[settings] }

requires:
    redaxo: '>=5.1.0'
    php:
        version: '>=5.3'
    packages:
        media_manager: '>=2.0.2'
        rex_redactor: '>=1.6.1'
        yform: '>=1.0-beta4'