package: d2u_machinery
version: '1.4.3'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_machinery

page:
    title: 'translate:d2u_machinery_meta_title'
    perm: 'd2u_machinery[]'
    icon: rex-icon rex-icon-module
    subpages:
        machine: { title: 'translate:d2u_machinery_meta_machines', icon: rex-icon rex-icon-module, perm: 'd2u_machinery[machine]' }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category, perm: 'd2u_machinery[category]' }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'd2u_machinery[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'd2u_machinery[settings]' }

requires:
    php: '>=8.0'
    redaxo: '>=5.10.0'
    packages:
        d2u_helper: '>=1.8.8'
        media_manager: '>=2.3'
        sprog: '>=1.0.0'
        url: '>=2.0'
        yform: '>=4.0'
        yrewrite: '>=2.0.1'
        
conflicts:
    packages:
        d2u_videos: '<1.1'
        
default_config:
    default_category_sort: 'name'
    default_machine_sort: 'name'
    show_categories_usage_area: 'hide'
    show_teaser: 'hide'
    show_techdata: 'show'
        
installer_ignore:
    - .github