package: d2u_machinery
version: '1.3.1'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_machinery

page:
    title: 'translate:d2u_machinery_meta_title'
    perm: d2u_machinery[]
    icon: rex-icon rex-icon-module
    subpages:
        machine: { title: 'translate:d2u_machinery_meta_machines', icon: rex-icon rex-icon-module, perm: d2u_machinery[machine] }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category, perm: d2u_machinery[category] }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_machinery[settings] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_machinery[settings] }

requires:
    packages:
        d2u_helper: '>=1.6.1'
        media_manager: '>=2.3'
        sprog: '>=1.0.0'
        url: '>=1.0.1'
        yform: '>=3.0'
        yrewrite: '>=2.0.1'