<?php

namespace TobiasKrais\D2UMachinery;

use rex_clang;
use rex_config;

/**
 * @api
 * Offers helper functions for language issues.
 */
class LangHelper extends \TobiasKrais\D2UHelper\ALangHelper
{
    /**
     * @var array<string,string> Array with englisch replacements. Key is the wildcard,
     * value the replacement.
     */
    public $replacements_english = [
        'd2u_machinery_advantages' => 'Benefits at a glance',
        'd2u_machinery_alternative_machines' => 'Alternative Machines',
        'd2u_machinery_additional_machines' => 'Supplementary Machines',
        'd2u_machinery_back_machine_list' => 'Go back to machine list',
        'd2u_machinery_consultation_heading' => 'Let us advise you',
        'd2u_machinery_consultation_hint' => 'Together we will find the best solution for you.<br><b>Please contact us.</b>',
        'd2u_machinery_consultation_link_machine' => 'Go to inquiry form',
        'd2u_machinery_consultation_link_personal' => 'For personal consultancy',
        'd2u_machinery_consultation_text' => 'We will help you to find the right product.',
        'd2u_machinery_dimensions_length' => 'Length',
        'd2u_machinery_dimensions_length_width_height' => 'Dimensions (L&nbsp;x&nbsp;W&nbsp;x&nbsp;H)',
        'd2u_machinery_dimensions_width_height_depth' => 'Dimensions (W&nbsp;x&nbsp;H&nbsp;x&nbsp;D)',
        'd2u_machinery_downloads' => 'Downloads',
        'd2u_machinery_engine_power' => 'Drive performance',
        'd2u_machinery_engine_power_frequency_controlled' => 'frequency controlled',
        'd2u_machinery_form_company' => 'Company',
        'd2u_machinery_form_fax' => 'Fax',
        'd2u_machinery_form_position' => 'function',
        'd2u_machinery_form_validate_company' => 'Please enter the company name.',
        'd2u_machinery_no_machines' => 'We are sorry. Currently we have no machines available. Please try again later.',
        'd2u_machinery_operating_voltage' => 'Operating voltage',
        'd2u_machinery_our_products' => 'Machines for Your Applications',
        'd2u_machinery_all_products' => 'All products',
        'd2u_machinery_overview' => 'Machine',
        'd2u_machinery_pics' => 'Pictures',
        'd2u_machinery_productfinder_heading' => 'Product Finder',
        'd2u_machinery_productfinder_text' => 'Find your product',
        'd2u_machinery_references' => 'Credentials',
        'd2u_machinery_request' => 'Inquiry',
        'd2u_machinery_service' => 'Service details',
        'd2u_machinery_software' => 'Software',
        'd2u_machinery_tech_data' => 'Technical&nbsp;Data',
        'd2u_machinery_unit_a' => 'A',
        'd2u_machinery_unit_a_mm' => '(a) mm',
        'd2u_machinery_unit_bar' => 'bar',
        'd2u_machinery_unit_cm' => 'cm',
        'd2u_machinery_unit_cm2' => 'cm²',
        'd2u_machinery_unit_ca' => 'approx.',
        'd2u_machinery_unit_diameter_mm' => 'Ø mm',
        'd2u_machinery_unit_degrees' => 'Degrees',
        'd2u_machinery_unit_hz' => 'Hz',
        'd2u_machinery_unit_kg' => 'kg',
        'd2u_machinery_unit_kg_m' => 'kg/m',
        'd2u_machinery_unit_kn' => 'kN',
        'd2u_machinery_unit_kw' => 'kW',
        'd2u_machinery_unit_l' => 'l',
        'd2u_machinery_unit_l_min' => 'l/min',
        'd2u_machinery_unit_m' => 'm',
        'd2u_machinery_unit_m2_h' => 'm²/h',
        'd2u_machinery_unit_m3' => 'm³',
        'd2u_machinery_unit_m_min' => 'm/min',
        'd2u_machinery_unit_min1' => 'min-1',
        'd2u_machinery_unit_mm' => 'mm',
        'd2u_machinery_unit_mm_min' => 'mm/min',
        'd2u_machinery_unit_pieces' => 'Pieces',
        'd2u_machinery_unit_rotations_min' => 'r/min',
        'd2u_machinery_unit_v' => 'V',
        'd2u_machinery_usage_areas' => 'Usage areas',
        'd2u_machinery_video' => 'Video',
        'd2u_machinery_weight' => 'Weight',
        'd2u_machinery_equipment' => 'Equipment',
        'd2u_machinery_equipment_artno' => 'Article No.',
        'd2u_machinery_export_linkedin_comment_text' => 'Check out our latest offer. For further information click on the picture.',
        'd2u_machinery_export_linkedin_details' => 'More information can be found on our website.',
        'd2u_machinery_export_linkedin_offers' => 'offers',
        'd2u_machinery_industry_sectors' => 'At Home in Your Industries',
        'd2u_machinery_agitator' => 'Agitator',
        'd2u_machinery_agitators_mpas' => 'mPas',
        'd2u_machinery_agitators_viscosity' => 'Viscosity up to',
        'd2u_machinery_construction_equipment_airless_hose_connection' => 'Hose connection',
        'd2u_machinery_construction_equipment_airless_hose_diameter' => 'Hose diameter',
        'd2u_machinery_construction_equipment_airless_hose_length' => 'Hose length',
        'd2u_machinery_construction_equipment_airless_nozzle_size' => 'Nozzle size',
        'd2u_machinery_construction_equipment_container_capacity' => 'Capacity',
        'd2u_machinery_construction_equipment_container_connection_port' => 'Connection Port',
        'd2u_machinery_construction_equipment_container_conveying_wave' => 'Conveying wave',
        'd2u_machinery_construction_equipment_container_mixing_performance' => 'Mixing performance',
        'd2u_machinery_construction_equipment_container_waterconnect' => 'Water connection',
        'd2u_machinery_construction_equipment_container_weight_empty' => 'Empty weight',
        'd2u_machinery_construction_equipment_cutters_cutting_depth' => 'Cutting depth',
        'd2u_machinery_construction_equipment_cutters_cutting_length' => 'Cutting length',
        'd2u_machinery_construction_equipment_cutters_rod_length' => 'Rod length',
        'd2u_machinery_construction_equipment_delivery_sets' => 'Scope of delivery',
        'd2u_machinery_construction_equipment_description_technical' => 'Comments',
        'd2u_machinery_construction_equipment_floor_beam_power_on_concrete' => 'Beam power on concrete',
        'd2u_machinery_construction_equipment_floor_dust_extraction_connection' => 'Dust extraction connection',
        'd2u_machinery_construction_equipment_floor_feedrate' => 'Feedrate',
        'd2u_machinery_construction_equipment_floor_filter_connection' => 'Filter connection',
        'd2u_machinery_construction_equipment_floor_rotations' => 'Rotations',
        'd2u_machinery_construction_equipment_floor_working_pressure' => 'Working pressure',
        'd2u_machinery_construction_equipment_floor_working_width' => 'Working width',
        'd2u_machinery_construction_equipment_grinder_grinding_plate' => 'Grinding plate',
        'd2u_machinery_construction_equipment_grinder_grinding_wheel' => 'Grinding wheels (Ø)',
        'd2u_machinery_construction_equipment_grinder_rotational_frequency' => 'Rotational frequency',
        'd2u_machinery_construction_equipment_grinder_sanding' => 'Sanding',
        'd2u_machinery_construction_equipment_grinder_vacuum_connection' => 'Vacuum connection (Ø)',
        'd2u_machinery_construction_equipment_machine_technique' => 'Machine technique',
        'd2u_machinery_construction_equipment_max' => 'max.',
        'd2u_machinery_construction_equipment_operating_pressure' => 'Operating pressure',
        'd2u_machinery_construction_equipment_pump_conveying_distance' => 'Conveying distance (depending on the material)',
        'd2u_machinery_construction_equipment_pump_filling' => 'Filling',
        'd2u_machinery_construction_equipment_pump_flow_volume' => 'Delivery rate (depending on the material)',
        'd2u_machinery_construction_equipment_pump_grain_size' => 'Grain size',
        'd2u_machinery_construction_equipment_pump_material_container' => 'Material container',
        'd2u_machinery_construction_equipment_pump_pressure_height' => 'Pressure height (depending on the material)',
        'd2u_machinery_construction_equipment_up_to' => 'up to',
        'd2u_machinery_construction_equipment_waste_water_capacity' => 'Capacity',
        'd2u_machinery_features' => 'Features',
        'd2u_machinery_options' => 'Options',
        'd2u_machinery_steel_automation_supply_ids' => 'Automation',
        'd2u_machinery_construction_equipment_service' => 'Service',
        'd2u_machinery_used_machines' => 'Used machines',
        'd2u_machinery_used_machines_availability' => 'Available',
        'd2u_machinery_used_machines_availible_from' => 'Available from',
        'd2u_machinery_used_machines_config_error' => 'Failure: in the D2U Machinery Addon settings is this article not configured.',
        'd2u_machinery_used_machines_details' => 'Details',
        'd2u_machinery_used_machines_external_url' => 'For more details, see',
        'd2u_machinery_used_machines_infos' => 'More information',
        'd2u_machinery_used_machines_link_machine' => 'More information on the type of machine',
        'd2u_machinery_used_machines_location' => 'Location',
        'd2u_machinery_used_machines_no_machines' => 'At the moment there are no demonstration / used machines available.',
        'd2u_machinery_used_machines_offer_rent' => 'Rental offer',
        'd2u_machinery_used_machines_offers_rent' => 'Rental offers',
        'd2u_machinery_used_machines_offers_sale' => 'Sale offers',
        'd2u_machinery_used_machines_price' => 'Price',
        'd2u_machinery_used_machines_price_on_request' => 'on request',
        'd2u_machinery_used_machines_vat_excluded' => 'without VAT',
        'd2u_machinery_used_machines_vat_included' => 'VAT included',
        'd2u_machinery_used_machines_year_built' => 'Year of construction',
    ];

    /**
     * @var array<string,string> Array with german replacements. Key is the wildcard,
     * value the replacement.
     */
    protected array $replacements_german = [
        'd2u_machinery_advantages' => 'Vorteile auf einen Blick',
        'd2u_machinery_alternative_machines' => 'Alternative Maschinen',
        'd2u_machinery_additional_machines' => 'Ergänzende Maschinen',
        'd2u_machinery_back_machine_list' => 'Zurück zur Maschinenliste',
        'd2u_machinery_consultation_heading' => 'Lassen Sie sich beraten',
        'd2u_machinery_consultation_hint' => 'Wir bieten für Ihren Bedarf die optimale Lösung.<br><b>Nehmen Sie Kontakt mit uns auf.</b>',
        'd2u_machinery_consultation_link_machine' => 'Zur Maschinenanfrage',
        'd2u_machinery_consultation_link_personal' => 'Zur persönlichen Beratung',
        'd2u_machinery_consultation_text' => 'Wir helfen Ihnen dabei, das passende<br>Produkt zu finden.',
        'd2u_machinery_dimensions_length' => 'Länge',
        'd2u_machinery_dimensions_length_width_height' => 'Maße (L&nbsp;x&nbsp;B&nbsp;x&nbsp;H)',
        'd2u_machinery_dimensions_width_height_depth' => 'Maße (B&nbsp;x&nbsp;H&nbsp;x&nbsp;T)',
        'd2u_machinery_downloads' => 'Downloads',
        'd2u_machinery_engine_power' => 'Motorleistung',
        'd2u_machinery_engine_power_frequency_controlled' => 'frequenzgeregelt',
        'd2u_machinery_form_company' => 'Firma',
        'd2u_machinery_form_fax' => 'Fax',
        'd2u_machinery_form_position' => 'Funktion',
        'd2u_machinery_form_validate_company' => 'Bitte geben Sie den Firmennamen an',
        'd2u_machinery_no_machines' => 'Es tut uns leid. Im Moment haben wir keine Angebote verfügbar. Bitte versuchen Sie es später noch einmal.',
        'd2u_machinery_operating_voltage' => 'Betriebsspannung',
        'd2u_machinery_our_products' => 'Maschinen für Ihren Einsatz',
        'd2u_machinery_all_products' => 'Alle Produkte',
        'd2u_machinery_overview' => 'Maschine',
        'd2u_machinery_pics' => 'Bilder',
        'd2u_machinery_productfinder_heading' => 'Produktfinder',
        'd2u_machinery_productfinder_text' => 'Finden Sie genau Ihr Produkt',
        'd2u_machinery_references' => 'Kundenerfahrungen',
        'd2u_machinery_request' => 'Anfrage',
        'd2u_machinery_service' => 'Service&nbsp;Details',
        'd2u_machinery_software' => 'Software',
        'd2u_machinery_tech_data' => 'Technische Daten',
        'd2u_machinery_unit_a' => 'A',
        'd2u_machinery_unit_a_mm' => '(a) mm',
        'd2u_machinery_unit_bar' => 'bar',
        'd2u_machinery_unit_cm' => 'cm',
        'd2u_machinery_unit_cm2' => 'cm²',
        'd2u_machinery_unit_ca' => 'ca.',
        'd2u_machinery_unit_diameter_mm' => 'Ø mm',
        'd2u_machinery_unit_degrees' => '°',
        'd2u_machinery_unit_hz' => 'Hz',
        'd2u_machinery_unit_kg' => 'kg',
        'd2u_machinery_unit_kg_m' => 'kg/m',
        'd2u_machinery_unit_kn' => 'kN',
        'd2u_machinery_unit_kw' => 'kW',
        'd2u_machinery_unit_l' => 'l',
        'd2u_machinery_unit_l_min' => 'l/min',
        'd2u_machinery_unit_m' => 'm',
        'd2u_machinery_unit_m2_h' => 'm²/h',
        'd2u_machinery_unit_m3' => 'm³',
        'd2u_machinery_unit_m_min' => 'm/min',
        'd2u_machinery_unit_min1' => 'min-1',
        'd2u_machinery_unit_mm' => 'mm',
        'd2u_machinery_unit_mm_min' => 'mm/min',
        'd2u_machinery_unit_pieces' => 'Stück',
        'd2u_machinery_unit_rotations_min' => 'U/min',
        'd2u_machinery_unit_v' => 'V',
        'd2u_machinery_usage_areas' => 'Anwendungsgebiete',
        'd2u_machinery_video' => 'Video',
        'd2u_machinery_weight' => 'Gewicht',
        'd2u_machinery_equipment' => 'Zubehör',
        'd2u_machinery_equipment_artno' => 'Artikelnummer',
        'd2u_machinery_export_linkedin_comment_text' => 'Unsere aktuellen Angebote: Klicken Sie auf das Bild.',
        'd2u_machinery_export_linkedin_details' => 'Mehr Infos finden Sie auf unserer Webseite.',
        'd2u_machinery_export_linkedin_offers' => 'bietet an',
        'd2u_machinery_industry_sectors' => 'Für Ihre Branche',
        'd2u_machinery_agitator' => 'Rührwerk',
        'd2u_machinery_agitators_mpas' => 'mPas',
        'd2u_machinery_agitators_viscosity' => 'Viskosität bis zu',
        'd2u_machinery_construction_equipment_airless_hose_connection' => 'Schlauchanschluss',
        'd2u_machinery_construction_equipment_airless_hose_diameter' => 'Schlauchdurchmesser',
        'd2u_machinery_construction_equipment_airless_hose_length' => 'Schlauchlänge',
        'd2u_machinery_construction_equipment_airless_nozzle_size' => 'Düsengröße',
        'd2u_machinery_construction_equipment_container_capacity' => 'Füllmenge',
        'd2u_machinery_construction_equipment_container_connection_port' => 'Anschluss',
        'd2u_machinery_construction_equipment_container_conveying_wave' => 'Förderwelle',
        'd2u_machinery_construction_equipment_container_mixing_performance' => 'Mischleistung',
        'd2u_machinery_construction_equipment_container_waterconnect' => 'Wasseranschluss',
        'd2u_machinery_construction_equipment_container_weight_empty' => 'Leergewicht',
        'd2u_machinery_construction_equipment_cutters_cutting_depth' => 'Schnitttiefe',
        'd2u_machinery_construction_equipment_cutters_cutting_length' => 'Schnittlänge',
        'd2u_machinery_construction_equipment_cutters_rod_length' => 'Stablänge',
        'd2u_machinery_construction_equipment_delivery_sets' => 'Lieferumfang',
        'd2u_machinery_construction_equipment_description_technical' => 'Bemerkungen',
        'd2u_machinery_construction_equipment_floor_beam_power_on_concrete' => 'Strahlleistung auf Beton',
        'd2u_machinery_construction_equipment_floor_dust_extraction_connection' => 'Anschluss Staubabsaugung',
        'd2u_machinery_construction_equipment_floor_feedrate' => 'Vorschub',
        'd2u_machinery_construction_equipment_floor_filter_connection' => 'Anschluss Filteranlage',
        'd2u_machinery_construction_equipment_floor_rotations' => 'Umdrehungen',
        'd2u_machinery_construction_equipment_floor_working_pressure' => 'Arbeitsdruck',
        'd2u_machinery_construction_equipment_floor_working_width' => 'Arbeitsbreite',
        'd2u_machinery_construction_equipment_grinder_grinding_plate' => 'Schleifplatte',
        'd2u_machinery_construction_equipment_grinder_grinding_wheel' => 'Schleifscheiben (Ø)',
        'd2u_machinery_construction_equipment_grinder_rotational_frequency' => 'Drehfrequenz',
        'd2u_machinery_construction_equipment_grinder_sanding' => 'Schleifhub',
        'd2u_machinery_construction_equipment_grinder_vacuum_connection' => 'Staubsaugeranschluss (Ø)',
        'd2u_machinery_construction_equipment_machine_technique' => 'Maschinentechnik',
        'd2u_machinery_construction_equipment_max' => 'max.',
        'd2u_machinery_construction_equipment_operating_pressure' => 'Betriebsdruck',
        'd2u_machinery_construction_equipment_pump_conveying_distance' => 'Förderweite (materialabhängig)',
        'd2u_machinery_construction_equipment_pump_filling' => 'Einfüllhöhe',
        'd2u_machinery_construction_equipment_pump_flow_volume' => 'Förderleistung (materialabhängig)',
        'd2u_machinery_construction_equipment_pump_grain_size' => 'Korngröße',
        'd2u_machinery_construction_equipment_pump_material_container' => 'Materialbehälter',
        'd2u_machinery_construction_equipment_pump_pressure_height' => 'Förderhöhe (materialabhängig)',
        'd2u_machinery_construction_equipment_up_to' => 'bis',
        'd2u_machinery_construction_equipment_waste_water_capacity' => 'Fassungsvermögen',
        'd2u_machinery_features' => 'Features',
        'd2u_machinery_options' => 'Optionen',
        'd2u_machinery_steel_automation_supply_ids' => 'Automatisierung',
        'd2u_machinery_construction_equipment_service' => 'Service',
        'd2u_machinery_used_machines' => 'Gebrauchtmaschinen',
        'd2u_machinery_used_machines_availability' => 'Sofort verfügbar',
        'd2u_machinery_used_machines_availible_from' => 'Verfügbar ab',
        'd2u_machinery_used_machines_config_error' => 'Fehler: in den Einstellungen der D2U Machinery Erweiterung ist dieser Artikel nicht konfiguriert.',
        'd2u_machinery_used_machines_details' => 'Details',
        'd2u_machinery_used_machines_external_url' => 'Details',
        'd2u_machinery_used_machines_infos' => 'Weitere Informationen',
        'd2u_machinery_used_machines_link_machine' => 'Weitere Informationen zum Maschinentyp',
        'd2u_machinery_used_machines_location' => 'Standort',
        'd2u_machinery_used_machines_no_machines' => 'Zur Zeit sind leider keine Vorführ-/Gebrauchtmaschinen vorhanden.',
        'd2u_machinery_used_machines_offers_rent' => 'Mietangebote',
        'd2u_machinery_used_machines_offers_sale' => 'Verkaufsangebote',
        'd2u_machinery_used_machines_offer_rent' => 'Mietangebot',
        'd2u_machinery_used_machines_price' => 'Preis',
        'd2u_machinery_used_machines_price_on_request' => 'auf Anfrage',
        'd2u_machinery_used_machines_vat_excluded' => 'ohne MwSt.',
        'd2u_machinery_used_machines_vat_included' => 'MwSt. enthalten',
        'd2u_machinery_used_machines_year_built' => 'Baujahr',
    ];

    /**
     * @var array<string,string> Array with french replacements. Key is the wildcard,
     * value the replacement.
     */
    protected array $replacements_french = [
        'd2u_machinery_advantages' => 'Les avantages en un coup d\'œil',
        'd2u_machinery_alternative_machines' => 'Machines alternatives',
        'd2u_machinery_additional_machines' => 'Machines complementaires',
        'd2u_machinery_back_machine_list' => 'Retour à la liste des machines',
        'd2u_machinery_consultation_heading' => 'Laissez vous conseiller',
        'd2u_machinery_consultation_hint' => 'Nous fournissons la solution optimale à vos besoins.<br><b>Contactez-nous.</b>',
        'd2u_machinery_consultation_link_machine' => 'Vers demande machine',
        'd2u_machinery_consultation_link_personal' => 'Pour un conseil personnalisé ',
        'd2u_machinery_consultation_text' => 'Nous vous aidons à trouver le bon <br> produit.',
        'd2u_machinery_dimensions_length' => 'Longueur',
        'd2u_machinery_dimensions_length_width_height' => 'Dimensions (L&nbsp;x&nbsp;L&nbsp;x&nbsp;H)',
        'd2u_machinery_dimensions_width_height_depth' => 'Dimensions  (L&nbsp;x&nbsp;H&nbsp;x&nbsp;P) ',
        'd2u_machinery_downloads' => 'Téléchargements',
        'd2u_machinery_engine_power' => 'Puissance moteur',
        'd2u_machinery_engine_power_frequency_controlled' => 'fréquence commandée',
        'd2u_machinery_form_company' => 'Société',
        'd2u_machinery_form_fax' => 'Télécopie',
        'd2u_machinery_form_position' => 'Fonction',
        'd2u_machinery_form_validate_company' => 'Veuillez indiquer votre société',
        'd2u_machinery_no_machines' => 'Nous sommes désolés. Pour le moment, nous n\'avons aucune offre disponible. Veuillez réessayer plus tard.',
        'd2u_machinery_operating_voltage' => 'tension de fonctionnement',
        'd2u_machinery_our_products' => 'Nos machines',
        'd2u_machinery_all_products' => 'Tous les produits',
        'd2u_machinery_overview' => 'Machine',
        'd2u_machinery_pics' => 'Photos',
        'd2u_machinery_productfinder_heading' => 'Recherche de produits',
        'd2u_machinery_productfinder_text' => 'Trouvez exactement votre produit',
        'd2u_machinery_references' => 'Références ',
        'd2u_machinery_request' => 'Demande',
        'd2u_machinery_service' => 'Détails du service',
        'd2u_machinery_software' => 'Logiciel',
        'd2u_machinery_tech_data' => 'Données techniques',
        'd2u_machinery_unit_a' => 'A',
        'd2u_machinery_unit_a_mm' => '(a) mm',
        'd2u_machinery_unit_bar' => 'bar',
        'd2u_machinery_unit_ca' => 'approx.',
        'd2u_machinery_unit_cm' => 'cm',
        'd2u_machinery_unit_cm2' => 'cm²',
        'd2u_machinery_unit_diameter_mm' => 'Ø mm',
        'd2u_machinery_unit_degrees' => '°',
        'd2u_machinery_unit_hz' => 'Hz',
        'd2u_machinery_unit_kg' => 'kg',
        'd2u_machinery_unit_kg_m' => 'kg/m',
        'd2u_machinery_unit_kn' => 'kN',
        'd2u_machinery_unit_kw' => 'kW',
        'd2u_machinery_unit_l' => 'l',
        'd2u_machinery_unit_l_min' => 'l/min',
        'd2u_machinery_unit_m' => 'm',
        'd2u_machinery_unit_m2_h' => 'm²/h',
        'd2u_machinery_unit_m3' => 'm³',
        'd2u_machinery_unit_m_min' => 'm/min',
        'd2u_machinery_unit_min1' => 'min-1',
        'd2u_machinery_unit_mm' => 'mm',
        'd2u_machinery_unit_mm_min' => 'mm/min',
        'd2u_machinery_unit_pieces' => 'Pièce',
        'd2u_machinery_unit_rotations_min' => 'r/min',
        'd2u_machinery_unit_v' => 'V',
        'd2u_machinery_usage_areas' => 'Procédés',
        'd2u_machinery_video' => 'Vidéo',
        'd2u_machinery_weight' => 'Poids',
        'd2u_machinery_equipment' => 'Accessoires',
        'd2u_machinery_equipment_artno' => 'Numéro d\'article',
        'd2u_machinery_industry_sectors' => 'Branches',
        'd2u_machinery_construction_equipment_airless_hose_connection' => 'Raccord de tuyau',
        'd2u_machinery_construction_equipment_airless_hose_diameter' => 'Diamètre du tuyau',
        'd2u_machinery_construction_equipment_airless_hose_length' => 'Longueur du tuyau',
        'd2u_machinery_construction_equipment_airless_nozzle_size' => 'Taille de la buse',
        'd2u_machinery_construction_equipment_container_capacity' => 'Capacité',
        'd2u_machinery_construction_equipment_container_connection_port' => 'Connexion',
        'd2u_machinery_construction_equipment_container_conveying_wave' => 'L\'arbre de convoyeur',
        'd2u_machinery_construction_equipment_container_mixing_performance' => 'Performances de mélange',
        'd2u_machinery_construction_equipment_container_waterconnect' => 'connexion d\'eau',
        'd2u_machinery_construction_equipment_container_weight_empty' => 'Poids à vide',
        'd2u_machinery_construction_equipment_cutters_cutting_depth' => 'Profondeur de coupe',
        'd2u_machinery_construction_equipment_cutters_cutting_length' => 'Durée moyenne',
        'd2u_machinery_construction_equipment_cutters_rod_length' => 'Tige de longueur',
        'd2u_machinery_construction_equipment_delivery_sets' => 'Contenu de la livraison',
        'd2u_machinery_construction_equipment_description_technical' => 'Commentaires',
        'd2u_machinery_construction_equipment_floor_beam_power_on_concrete' => 'Puissance de faisceau sur le béton',
        'd2u_machinery_construction_equipment_floor_dust_extraction_connection' => 'Extraction de poussière de connexion',
        'd2u_machinery_construction_equipment_floor_feedrate' => 'Vitesse d\'avance',
        'd2u_machinery_construction_equipment_floor_filter_connection' => 'Système de filtre de connexion',
        'd2u_machinery_construction_equipment_floor_rotations' => 'Révolutions',
        'd2u_machinery_construction_equipment_floor_working_pressure' => 'Pression de travail',
        'd2u_machinery_construction_equipment_floor_working_width' => 'Largeur de travail',
        'd2u_machinery_construction_equipment_grinder_grinding_plate' => 'Surface de meulage',
        'd2u_machinery_construction_equipment_grinder_grinding_wheel' => 'Meule (Ø)',
        'd2u_machinery_construction_equipment_grinder_rotational_frequency' => 'Fréquence de rotation',
        'd2u_machinery_construction_equipment_grinder_sanding' => 'Ponçage',
        'd2u_machinery_construction_equipment_grinder_vacuum_connection' => 'Raccord du vide (Ø)',
        'd2u_machinery_construction_equipment_machine_technique' => 'Technologie de la machine',
        'd2u_machinery_construction_equipment_max' => 'max.',
        'd2u_machinery_construction_equipment_operating_pressure' => 'Pression de service',
        'd2u_machinery_construction_equipment_pump_conveying_distance' => 'Conveying distance (en fonction du matériau)',
        'd2u_machinery_construction_equipment_pump_filling' => 'Remplissage',
        'd2u_machinery_construction_equipment_pump_flow_volume' => 'Volume d\'écoulement (en fonction du matériau)',
        'd2u_machinery_construction_equipment_pump_grain_size' => 'Taille des grains',
        'd2u_machinery_construction_equipment_pump_material_container' => 'Réservoir de matière',
        'd2u_machinery_construction_equipment_pump_pressure_height' => 'Hauteur de pression (en fonction du matériau)',
        'd2u_machinery_construction_equipment_up_to' => 'à',
        'd2u_machinery_construction_equipment_waste_water_capacity' => 'Capacité',
        'd2u_machinery_features' => 'Caractéristiques',
        'd2u_machinery_options' => 'Options',
        'd2u_machinery_steel_automation_supply_ids' => 'Automatisation',
        'd2u_machinery_construction_equipment_service' => 'Service',
        'd2u_machinery_used_machines' => 'Machines d\'occasion',
        'd2u_machinery_used_machines_availability' => 'Disponible dès maintenant',
        'd2u_machinery_used_machines_availible_from' => 'Disponible à partir',
        'd2u_machinery_used_machines_config_error' => 'translation missing: d2u_machinery_used_machines_config_error',
        'd2u_machinery_used_machines_details' => 'Détails',
        'd2u_machinery_used_machines_external_url' => 'Détails',
        'd2u_machinery_used_machines_infos' => 'Plus d\'informations',
        'd2u_machinery_used_machines_link_machine' => 'Informations complémentaires au type de machine',
        'd2u_machinery_used_machines_location' => 'translation missing: d2u_machinery_used_machines_location',
        'd2u_machinery_used_machines_no_machines' => 'Pour l\'instant, démonstration / machines d\'occasion ne sont pas disponibles.',
        'd2u_machinery_used_machines_offer_rent' => 'translation missing: d2u_machinery_used_machines_offer_rent',
        'd2u_machinery_used_machines_offers_rent' => 'translation missing: d2u_machinery_used_machines_offers_rent',
        'd2u_machinery_used_machines_offers_sale' => 'translation missing: d2u_machinery_used_machines_offers_sale',
        'd2u_machinery_used_machines_price' => 'translation missing: d2u_machinery_used_machines_price',
        'd2u_machinery_used_machines_price_on_request' => 'translation missing: d2u_machinery_used_machines_price_on_request',
        'd2u_machinery_used_machines_vat_excluded' => 'translation missing: d2u_machinery_used_machines_vat_excluded',
        'd2u_machinery_used_machines_vat_included' => 'translation missing: d2u_machinery_used_machines_vat_included',
        'd2u_machinery_used_machines_year_built' => 'L\'année de construction',
    ];

    /**
     * @var array<string,string> Array with spanish replacements. Key is the wildcard,
     * value the replacement.
     */
    protected array $replacements_spanish = [
        'd2u_machinery_advantages' => 'Ventajas de un vistazo',
        'd2u_machinery_alternative_machines' => 'Máquinas alternativas',
        'd2u_machinery_additional_machines' => 'Máquinas complementarias',
        'd2u_machinery_back_machine_list' => 'Volver a la lista de máquinas',
        'd2u_machinery_consultation_heading' => 'Déjese asesorar',
        'd2u_machinery_consultation_hint' => 'Brindamos la solución óptima para sus necesidades.<br><b>Contáctenos.</b>',
        'd2u_machinery_consultation_link_machine' => 'Ir a formulario de consulta.',
        'd2u_machinery_consultation_link_personal' => 'Para la consultora personal.',
        'd2u_machinery_consultation_text' => 'Le ayudamos a encontrar la empresa<br> producto adecuado.',
        'd2u_machinery_dimensions_length' => 'Longitud',
        'd2u_machinery_dimensions_length_width_height' => 'Dimensiones (L&nbsp;x&nbsp;An&nbsp;x&nbsp;Al)',
        'd2u_machinery_dimensions_width_height_depth' => 'Dimensiones (An&nbsp;x&nbsp;Al&nbsp;x&nbsp;P)',
        'd2u_machinery_downloads' => 'Descargas',
        'd2u_machinery_engine_power' => 'Potencia del motor',
        'd2u_machinery_engine_power_frequency_controlled' => 'Controlada por frecuencia',
        'd2u_machinery_form_company' => 'Empresa',
        'd2u_machinery_form_fax' => 'Fax',
        'd2u_machinery_form_position' => 'Sector de actividad',
        'd2u_machinery_no_machines' => 'No se encontraron máquinas.',
        'd2u_machinery_operating_voltage' => 'Tensión de servicio',
        'd2u_machinery_our_products' => 'Nuestras máquinas',
        'd2u_machinery_all_products' => 'Todos los productos',
        'd2u_machinery_overview' => 'Máquina',
        'd2u_machinery_pics' => 'Imágenes',
        'd2u_machinery_productfinder_heading' => 'Buscador de productos',
        'd2u_machinery_productfinder_text' => 'Encontrar exactamente su producto',
        'd2u_machinery_references' => 'Cartas credenciales',
        'd2u_machinery_request' => 'Solicitud',
        'd2u_machinery_service' => 'Detalles del servicio',
        'd2u_machinery_software' => 'Software',
        'd2u_machinery_tech_data' => 'Especificaciones técnicas',
        'd2u_machinery_unit_a' => 'A',
        'd2u_machinery_unit_a_mm' => '(a) mm',
        'd2u_machinery_unit_bar' => 'bar',
        'd2u_machinery_unit_ca' => 'aprox.',
        'd2u_machinery_unit_cm' => 'cm',
        'd2u_machinery_unit_cm2' => 'cm²',
        'd2u_machinery_unit_degrees' => '°',
        'd2u_machinery_unit_diameter_mm' => 'Ø mm',
        'd2u_machinery_unit_hz' => 'Hz',
        'd2u_machinery_unit_kg' => 'kg',
        'd2u_machinery_unit_kg_m' => 'kg/m',
        'd2u_machinery_unit_kn' => 'kN',
        'd2u_machinery_unit_kw' => 'kW',
        'd2u_machinery_unit_l' => 'l',
        'd2u_machinery_unit_l_min' => 'l/min',
        'd2u_machinery_unit_m' => 'm',
        'd2u_machinery_unit_m2_h' => 'm²/h',
        'd2u_machinery_unit_m3' => 'm³',
        'd2u_machinery_unit_m_min' => 'm/min',
        'd2u_machinery_unit_min1' => 'min-1',
        'd2u_machinery_unit_mm' => 'mm',
        'd2u_machinery_unit_mm_min' => 'mm/min',
        'd2u_machinery_unit_pieces' => 'Pieza',
        'd2u_machinery_unit_rotations_min' => 'r/min',
        'd2u_machinery_unit_v' => 'V',
        'd2u_machinery_usage_areas' => 'Operaciones',
        'd2u_machinery_video' => 'Vídeo',
        'd2u_machinery_weight' => 'Peso',
        'd2u_machinery_industry_sectors' => 'Industrias',
        'd2u_machinery_features' => 'Características',
        'd2u_machinery_options' => 'Opciones',
        'd2u_machinery_steel_automation_supply_ids' => 'Automatización',
        'd2u_machinery_used_machines' => 'Maquinaria usada',
        'd2u_machinery_used_machines_availability' => 'Ya disponible',
        'd2u_machinery_used_machines_availible_from' => 'Disponible a partir de',
        'd2u_machinery_used_machines_config_error' => 'Fallo: en la configuración del complemento de maquinaria D2U, este artículo no está configurado.',
        'd2u_machinery_used_machines_details' => 'Detalles',
        'd2u_machinery_used_machines_external_url' => 'Detalles',
        'd2u_machinery_used_machines_infos' => 'Para obtener más información',
        'd2u_machinery_used_machines_link_machine' => 'Más información sobre el tipo de máquina',
        'd2u_machinery_used_machines_location' => 'Ubicación',
        'd2u_machinery_used_machines_no_machines' => 'De momento no hay máquinas de demo / usadas disponibles',
        'd2u_machinery_used_machines_offer_rent' => 'Oferta de alquiler',
        'd2u_machinery_used_machines_offers_rent' => 'Oferta de alquiler',
        'd2u_machinery_used_machines_offers_sale' => 'Ofertas de venta',
        'd2u_machinery_used_machines_price' => 'Precio',
        'd2u_machinery_used_machines_price_on_request' => 'Precio maquinaria usada bajo petición',
        'd2u_machinery_used_machines_vat_excluded' => 'IVA no incluido',
        'd2u_machinery_used_machines_vat_included' => 'IVA incluido',
        'd2u_machinery_used_machines_year_built' => 'Año de construcción',
    ];

    /**
     * @var array<string,string> Array with dutch replacements. Key is the wildcard,
     * value the replacement.
     */
    protected array $replacements_dutch = [
        'd2u_machinery_advantages' => 'Voordelen in een oogopslag',
        'd2u_machinery_alternative_machines' => 'Alternatieve machines',
        'd2u_machinery_additional_machines' => 'Aanvullende machines',
        'd2u_machinery_back_machine_list' => 'Terug naar de machinelijst',
        'd2u_machinery_consultation_heading' => 'Laat ons u adviseren',
        'd2u_machinery_consultation_hint' => 'Wij bieden de optimale oplossing voor uw behoeften.<br><b>Neem contact met ons op.</b>',
        'd2u_machinery_consultation_link_machine' => 'Naar de machine-aanvraag.',
        'd2u_machinery_consultation_link_personal' => 'Voor persoonlijk advies',
        'd2u_machinery_consultation_text' => 'Wij helpen u de juiste <br> product te vinden.',
        'd2u_machinery_dimensions_length' => 'Lengte',
        'd2u_machinery_dimensions_length_width_height' => 'Afmetingen (l&nbsp;x&nbsp;b&nbsp;x&nbsp;h) ',
        'd2u_machinery_dimensions_width_height_depth' => 'Afmetingen (b&nbsp;x&nbsp;h&nbsp;x&nbsp;d)',
        'd2u_machinery_downloads' => 'Downloads',
        'd2u_machinery_engine_power' => 'Motorvermogen ',
        'd2u_machinery_engine_power_frequency_controlled' => 'frequentiegestuurd',
        'd2u_machinery_form_company' => 'Vennootschap',
        'd2u_machinery_form_fax' => 'Telefax',
        'd2u_machinery_form_position' => 'Werkterrein',
        'd2u_machinery_no_machines' => 'Geen machines gevonden.',
        'd2u_machinery_operating_voltage' => 'Bedrijfsspanning',
        'd2u_machinery_our_products' => 'Onze machines',
        'd2u_machinery_all_products' => 'Alle producten',
        'd2u_machinery_overview' => 'Machine',
        'd2u_machinery_pics' => 'Afbeeldingen',
        'd2u_machinery_productfinder_heading' => 'Productvinder',
        'd2u_machinery_productfinder_text' => 'Vind precies uw product',
        'd2u_machinery_references' => 'Geloofsbrieven',
        'd2u_machinery_request' => 'Aanvraag',
        'd2u_machinery_service' => 'Servicedetails',
        'd2u_machinery_software' => 'Software',
        'd2u_machinery_tech_data' => 'Technische gegevens',
        'd2u_machinery_unit_a' => 'A',
        'd2u_machinery_unit_a_mm' => '(a) mm',
        'd2u_machinery_unit_bar' => 'bar',
        'd2u_machinery_unit_ca' => 'ca.',
        'd2u_machinery_unit_cm' => 'cm',
        'd2u_machinery_unit_cm2' => 'cm²',
        'd2u_machinery_unit_diameter_mm' => 'Ø mm',
        'd2u_machinery_unit_degrees' => '°',
        'd2u_machinery_unit_hz' => 'Hz',
        'd2u_machinery_unit_kg' => 'kg',
        'd2u_machinery_unit_kg_m' => 'kg/m',
        'd2u_machinery_unit_kn' => 'kN',
        'd2u_machinery_unit_kw' => 'kW',
        'd2u_machinery_unit_l' => 'l',
        'd2u_machinery_unit_l_min' => 'l/min',
        'd2u_machinery_unit_m' => 'm',
        'd2u_machinery_unit_m2_h' => 'm²/h',
        'd2u_machinery_unit_m3' => 'm³',
        'd2u_machinery_unit_m_min' => 'm/min',
        'd2u_machinery_unit_min1' => 'min-1',
        'd2u_machinery_unit_mm' => 'mm',
        'd2u_machinery_unit_mm_min' => 'mm/min',
        'd2u_machinery_unit_pieces' => 'Stuks',
        'd2u_machinery_unit_rotations_min' => 'r/min',
        'd2u_machinery_unit_v' => 'V',
        'd2u_machinery_usage_areas' => 'Operaties',
        'd2u_machinery_video' => 'Video',
        'd2u_machinery_weight' => 'Gewicht',
        'd2u_machinery_industry_sectors' => 'Sectoren',
        'd2u_machinery_features' => 'Kenmerken',
        'd2u_machinery_options' => 'Opties',
        'd2u_machinery_steel_automation_supply_ids' => 'Automatisering',
        'd2u_machinery_used_machines' => 'translation missing: d2u_machinery_used_machines',
        'd2u_machinery_used_machines_availability' => 'Nu beschikbaar',
        'd2u_machinery_used_machines_availible_from' => 'Beschikbaar vanaf',
        'd2u_machinery_used_machines_config_error' => 'translation missing: d2u_machinery_used_machines_config_error',
        'd2u_machinery_used_machines_details' => 'Details',
        'd2u_machinery_used_machines_external_url' => 'Details',
        'd2u_machinery_used_machines_infos' => 'Voor meer informatie',
        'd2u_machinery_used_machines_link_machine' => 'translation missing: d2u_machinery_used_machines_link_machine',
        'd2u_machinery_used_machines_location' => 'translation missing: d2u_machinery_used_machines_location',
        'd2u_machinery_used_machines_no_machines' => 'translation missing: d2u_machinery_used_machines_no_machines',
        'd2u_machinery_used_machines_offer_rent' => 'translation missing: d2u_machinery_used_machines_offer_rent',
        'd2u_machinery_used_machines_offers_rent' => 'translation missing: d2u_machinery_used_machines_offers_rent',
        'd2u_machinery_used_machines_offers_sale' => 'translation missing: d2u_machinery_used_machines_offers_sale',
        'd2u_machinery_used_machines_price' => 'translation missing: d2u_machinery_used_machines_price',
        'd2u_machinery_used_machines_price_on_request' => 'translation missing: d2u_machinery_used_machines_price_on_request',
        'd2u_machinery_used_machines_vat_excluded' => 'translation missing: d2u_machinery_used_machines_vat_excluded',
        'd2u_machinery_used_machines_vat_included' => 'translation missing: d2u_machinery_used_machines_vat_included',
        'd2u_machinery_used_machines_year_built' => 'Bouwjaar',
    ];

    /**
     * @var array<string,string> Array with russian replacements. Key is the wildcard,
     * value the replacement.
     */
    protected array $replacements_russian = [
        'd2u_machinery_advantages' => 'Основные преимущества',
        'd2u_machinery_alternative_machines' => 'Альтернативные станки',
        'd2u_machinery_additional_machines' => 'Дополняющие станки',
        'd2u_machinery_back_machine_list' => 'Вернуться к списку оборудования',
        'd2u_machinery_consultation_heading' => 'Получите консультацию специалиста',
        'd2u_machinery_consultation_hint' => 'Мы предлагаем оптимальное решение для Вашего производства.<br><b>Свяжитесь с нами.</b>',
        'd2u_machinery_consultation_link_machine' => 'Отправить запрос',
        'd2u_machinery_consultation_link_personal' => 'Отправить запрос',
        'd2u_machinery_consultation_text' => 'Мы поможем Вам подобрать оборудование <br> в соответствии с техническими требованиями Вашего производства.',
        'd2u_machinery_dimensions_length' => 'длина',
        'd2u_machinery_dimensions_length_width_height' => 'габариты (д&nbsp;x&nbsp;ш&nbsp;x&nbsp;в) ',
        'd2u_machinery_dimensions_width_height_depth' => 'Размеры (ш&nbsp;x&nbsp;в&nbsp;x&nbsp;г) ',
        'd2u_machinery_downloads' => 'Загрузки',
        'd2u_machinery_engine_power' => 'мощность двигателя',
        'd2u_machinery_engine_power_frequency_controlled' => 'с регулируемой частотой',
        'd2u_machinery_form_company' => 'Компания',
        'd2u_machinery_form_fax' => 'Телефакс',
        'd2u_machinery_form_position' => 'Сфера деятельности',
        'd2u_machinery_form_validate_company' => 'Укажите название компании.',
        'd2u_machinery_no_machines' => 'Оборудование не найдено',
        'd2u_machinery_operating_voltage' => 'рабочее напряжение',
        'd2u_machinery_our_products' => 'Наше оборудование',
        'd2u_machinery_all_products' => 'Вся продукция',
        'd2u_machinery_overview' => 'Оборудование',
        'd2u_machinery_pics' => 'Фотографии',
        'd2u_machinery_productfinder_heading' => 'Поиск оборудования',
        'd2u_machinery_productfinder_text' => 'Подобрать оборудование',
        'd2u_machinery_references' => 'полномочия',
        'd2u_machinery_request' => 'запрос',
        'd2u_machinery_service' => 'Сведения об услугах',
        'd2u_machinery_software' => 'Программное обеспечение',
        'd2u_machinery_tech_data' => 'Технические характеристики',
        'd2u_machinery_unit_a' => 'A',
        'd2u_machinery_unit_a_mm' => '(a) мм',
        'd2u_machinery_unit_bar' => 'бар',
        'd2u_machinery_unit_ca' => 'примерно',
        'd2u_machinery_unit_cm' => 'см',
        'd2u_machinery_unit_cm2' => 'см²',
        'd2u_machinery_unit_degrees' => '°',
        'd2u_machinery_unit_diameter_mm' => 'Ø мм',
        'd2u_machinery_unit_hz' => 'Гц',
        'd2u_machinery_unit_kg' => 'кг',
        'd2u_machinery_unit_kg_m' => 'кг / м',
        'd2u_machinery_unit_kn' => 'кН',
        'd2u_machinery_unit_kw' => 'кВт',
        'd2u_machinery_unit_l' => 'l',
        'd2u_machinery_unit_l_min' => 'л/мин',
        'd2u_machinery_unit_m' => 'м',
        'd2u_machinery_unit_m2_h' => 'м²/ч',
        'd2u_machinery_unit_m3' => 'м³',
        'd2u_machinery_unit_m_min' => 'м/мин',
        'd2u_machinery_unit_min1' => 'мин-1',
        'd2u_machinery_unit_mm' => 'мм',
        'd2u_machinery_unit_mm_min' => 'мм/мин',
        'd2u_machinery_unit_pieces' => 'шт.',
        'd2u_machinery_unit_rotations_min' => 'оборотов/минуту',
        'd2u_machinery_unit_v' => 'В',
        'd2u_machinery_usage_areas' => 'операции',
        'd2u_machinery_video' => 'видео',
        'd2u_machinery_weight' => 'вес',
        'd2u_machinery_export_linkedin_comment_text' => 'Ознакомьтесь с нашими новыми предложениями. Для получения дополнительной информации нажмите на картинку.',
        'd2u_machinery_export_linkedin_details' => 'Подробную информацию Вы найдете на нашем сайте.',
        'd2u_machinery_export_linkedin_offers' => 'Предложения',
        'd2u_machinery_industry_sectors' => 'Отрасли',
        'd2u_machinery_features' => 'Функциональные возможности',
        'd2u_machinery_options' => 'Параметры',
        'd2u_machinery_steel_automation_supply_ids' => 'Автоматизация',
        'd2u_machinery_used_machines' => 'б/у оборудование',
        'd2u_machinery_used_machines_availability' => 'в наличии',
        'd2u_machinery_used_machines_availible_from' => 'Доступна с',
        'd2u_machinery_used_machines_config_error' => 'Ошибка: в настройках D2U Machinery Extension эта статья не настроена.',
        'd2u_machinery_used_machines_details' => 'Детали',
        'd2u_machinery_used_machines_external_url' => 'Детали',
        'd2u_machinery_used_machines_infos' => 'Для получения дополнительной информации',
        'd2u_machinery_used_machines_link_machine' => 'Дополнительная информация о станке',
        'd2u_machinery_used_machines_location' => 'место',
        'd2u_machinery_used_machines_no_machines' => 'На данный момент нет доступных подержанных машин.',
        'd2u_machinery_used_machines_offers_rent' => 'жилье',
        'd2u_machinery_used_machines_offers_sale' => 'товары для продажи',
        'd2u_machinery_used_machines_offer_rent' => 'жилье',
        'd2u_machinery_used_machines_price' => 'цена',
        'd2u_machinery_used_machines_price_on_request' => 'по запросу',
        'd2u_machinery_used_machines_vat_excluded' => 'без НДС',
        'd2u_machinery_used_machines_vat_included' => 'НДС включен',
        'd2u_machinery_used_machines_year_built' => 'год выпуска',
    ];

    /**
     * @var array<string,string> Array with portuguese replacements. Key is the wildcard,
     * value the replacement.
     */
    protected array $replacements_portuguese = [
        'd2u_machinery_advantages' => 'Resumo das vantagens',
        'd2u_machinery_alternative_machines' => 'Máquinas alternativas',
        'd2u_machinery_additional_machines' => 'Máquinas complementares',
        'd2u_machinery_back_machine_list' => 'De volta à lista de máquinas',
        'd2u_machinery_consultation_heading' => 'Vamos orientá-lo',
        'd2u_machinery_consultation_hint' => 'Fornecemos a solução ideal para suas necessidades.<br><b>Entre em contato.</b>',
        'd2u_machinery_consultation_link_machine' => 'Para o inquérito da máquina.',
        'd2u_machinery_consultation_link_personal' => 'Para consultoria pessoal',
        'd2u_machinery_consultation_text' => 'Nós ajudá-lo a encontrar o <br> produto certo.',
        'd2u_machinery_dimensions_length' => 'Comprimento',
        'd2u_machinery_dimensions_length_width_height' => 'Dimensões (C&nbsp;x&nbsp;L&nbsp;x&nbsp;A)',
        'd2u_machinery_dimensions_width_height_depth' => 'Dimensões (L&nbsp;x&nbsp;A&nbsp;x&nbsp;P',
        'd2u_machinery_downloads' => 'De downloads',
        'd2u_machinery_engine_power' => 'Potência do motor',
        'd2u_machinery_engine_power_frequency_controlled' => 'freqüência controlada',
        'd2u_machinery_form_company' => 'Empresa',
        'd2u_machinery_form_fax' => 'Fax',
        'd2u_machinery_form_position' => 'Área de actividade',
        'd2u_machinery_no_machines' => 'Nenhuma máquina encontrada.',
        'd2u_machinery_operating_voltage' => 'Tensão de operação',
        'd2u_machinery_our_products' => 'As nossas máquinas',
        'd2u_machinery_all_products' => 'Todos os produtos',
        'd2u_machinery_overview' => 'Máquina',
        'd2u_machinery_pics' => 'Pictures',
        'd2u_machinery_productfinder_heading' => 'Encontre o seu produto',
        'd2u_machinery_productfinder_text' => 'Encontre exatamente o seu produto',
        'd2u_machinery_references' => 'Credenciais',
        'd2u_machinery_request' => 'Consulta',
        'd2u_machinery_service' => 'Detalhes do serviço',
        'd2u_machinery_software' => 'Programa de computador',
        'd2u_machinery_tech_data' => 'Dados técnicos',
        'd2u_machinery_unit_a' => 'A',
        'd2u_machinery_unit_a_mm' => '(a) mm',
        'd2u_machinery_unit_bar' => 'bar',
        'd2u_machinery_unit_ca' => 'aprox.',
        'd2u_machinery_unit_cm' => 'cm',
        'd2u_machinery_unit_cm2' => 'cm²',
        'd2u_machinery_unit_diameter_mm' => 'mm',
        'd2u_machinery_unit_degrees' => '°',
        'd2u_machinery_unit_hz' => 'Hz',
        'd2u_machinery_unit_kg' => 'kg',
        'd2u_machinery_unit_kg_m' => 'kg/m',
        'd2u_machinery_unit_kn' => 'kN',
        'd2u_machinery_unit_kw' => 'kW',
        'd2u_machinery_unit_l' => 'l',
        'd2u_machinery_unit_l_min' => 'l/min',
        'd2u_machinery_unit_m' => 'm',
        'd2u_machinery_unit_m2_h' => 'm²/h',
        'd2u_machinery_unit_m3' => 'm³',
        'd2u_machinery_unit_m_min' => 'm/min',
        'd2u_machinery_unit_min1' => 'min-1',
        'd2u_machinery_unit_mm' => 'mm',
        'd2u_machinery_unit_mm_min' => 'mm/min',
        'd2u_machinery_unit_pieces' => 'Qtd.',
        'd2u_machinery_unit_rotations_min' => 'r/min',
        'd2u_machinery_unit_v' => 'V',
        'd2u_machinery_usage_areas' => 'Operações',
        'd2u_machinery_video' => 'Vídeo',
        'd2u_machinery_weight' => 'Peso',
        'd2u_machinery_industry_sectors' => 'Setores',
        'd2u_machinery_features' => 'Características',
        'd2u_machinery_options' => 'Opções',
        'd2u_machinery_steel_automation_supply_ids' => 'Automação',
        'd2u_machinery_used_machines' => 'translation missing: d2u_machinery_used_machines',
        'd2u_machinery_used_machines_availability' => 'Disponível agora',
        'd2u_machinery_used_machines_availible_from' => 'Disponível a partir de',
        'd2u_machinery_used_machines_config_error' => 'translation missing: d2u_machinery_used_machines_config_error',
        'd2u_machinery_used_machines_details' => 'detalhes',
        'd2u_machinery_used_machines_external_url' => 'detalhes',
        'd2u_machinery_used_machines_infos' => 'Para mais informações',
        'd2u_machinery_used_machines_link_machine' => 'translation missing: d2u_machinery_used_machines_link_machine',
        'd2u_machinery_used_machines_location' => 'translation missing: d2u_machinery_used_machines_location',
        'd2u_machinery_used_machines_no_machines' => 'translation missing: d2u_machinery_used_machines_no_machines',
        'd2u_machinery_used_machines_offer_rent' => 'translation missing: d2u_machinery_used_machines_offer_rent',
        'd2u_machinery_used_machines_offers_rent' => 'translation missing: d2u_machinery_used_machines_offers_rent',
        'd2u_machinery_used_machines_offers_sale' => 'translation missing: d2u_machinery_used_machines_offers_sale',
        'd2u_machinery_used_machines_price' => 'translation missing: d2u_machinery_used_machines_price',
        'd2u_machinery_used_machines_price_on_request' => 'translation missing: d2u_machinery_used_machines_price_on_request',
        'd2u_machinery_used_machines_vat_excluded' => 'translation missing: d2u_machinery_used_machines_vat_excluded',
        'd2u_machinery_used_machines_vat_included' => 'translation missing: d2u_machinery_used_machines_vat_included',
        'd2u_machinery_used_machines_year_built' => 'translation missing: d2u_machinery_used_machines_year_built',
    ];

    /**
     * @var array<string,string> Array with chinese replacements. Key is the wildcard,
     * value the replacement.
     */
    protected array $replacements_chinese = [
        'd2u_machinery_advantages' => '显而易见的优势',
        'd2u_machinery_alternative_machines' => '替代机器',
        'd2u_machinery_additional_machines' => '补充机器',
        'd2u_machinery_back_machine_list' => '回到機器列表',
        'd2u_machinery_consultation_heading' => '请获取建议',
        'd2u_machinery_consultation_hint' => '我們為您的需求提供最佳解決方案。<br><b>聯繫我們。</b>',
        'd2u_machinery_consultation_link_machine' => '机器询价',
        'd2u_machinery_consultation_link_personal' => '个人咨询',
        'd2u_machinery_consultation_text' => '我们将帮助您找到合适的产品。',
        'd2u_machinery_dimensions_length' => '长',
        'd2u_machinery_dimensions_length_width_height' => '体积（长度x宽度x高度）',
        'd2u_machinery_dimensions_width_height_depth' => '体积（宽度x高度x深度）',
        'd2u_machinery_downloads' => '新用户/改装套件',
        'd2u_machinery_engine_power' => '电机功率',
        'd2u_machinery_engine_power_frequency_controlled' => '频率控制',
        'd2u_machinery_form_company' => '公司',
        'd2u_machinery_form_fax' => '传真',
        'd2u_machinery_form_position' => '职能',
        'd2u_machinery_form_validate_company' => '请输入您的公司名',
        'd2u_machinery_no_machines' => '对不起 目前我们没有机器可用。 请稍后再试。',
        'd2u_machinery_operating_voltage' => '工作电压',
        'd2u_machinery_our_products' => '最适合您应用的设备和机器',
        'd2u_machinery_all_products' => '所有产品',
        'd2u_machinery_overview' => '机器',
        'd2u_machinery_pics' => '图片',
        'd2u_machinery_productfinder_heading' => '产品搜索器',
        'd2u_machinery_productfinder_text' => '找到您的理想产品',
        'd2u_machinery_references' => '参考',
        'd2u_machinery_request' => '问询',
        'd2u_machinery_service' => '服務細節',
        'd2u_machinery_software' => '软件',
        'd2u_machinery_tech_data' => '技术数据',
        'd2u_machinery_unit_a' => '安培',
        'd2u_machinery_unit_a_mm' => '(a) 毫米',
        'd2u_machinery_unit_bar' => '巴',
        'd2u_machinery_unit_ca' => '约',
        'd2u_machinery_unit_cm' => '公分',
        'd2u_machinery_unit_cm2' => '平方厘米',
        'd2u_machinery_unit_diameter_mm' => 'Ø 毫米',
        'd2u_machinery_unit_degrees' => '°',
        'd2u_machinery_unit_hz' => '赫兹',
        'd2u_machinery_unit_kg' => '公斤',
        'd2u_machinery_unit_kg_m' => '公斤/计',
        'd2u_machinery_unit_kn' => '千牛顿',
        'd2u_machinery_unit_kw' => '千瓦',
        'd2u_machinery_unit_l' => '升',
        'd2u_machinery_unit_l_min' => '升/最低',
        'd2u_machinery_unit_m' => '计',
        'd2u_machinery_unit_m2_h' => '平方米/小时',
        'd2u_machinery_unit_m3' => '立方米',
        'd2u_machinery_unit_m_min' => '计/最低',
        'd2u_machinery_unit_min1' => '最低-1',
        'd2u_machinery_unit_mm' => '毫米',
        'd2u_machinery_unit_mm_min' => '毫米/最低',
        'd2u_machinery_unit_pieces' => '块',
        'd2u_machinery_unit_rotations_min' => '转/分钟',
        'd2u_machinery_unit_v' => '伏特',
        'd2u_machinery_usage_areas' => '工艺支持',
        'd2u_machinery_video' => '视频',
        'd2u_machinery_weight' => '重量',
        'd2u_machinery_industry_sectors' => '行业',
        'd2u_machinery_features' => '特点',
        'd2u_machinery_options' => '选项',
        'd2u_machinery_steel_automation_supply_ids' => '自动化',
        'd2u_machinery_used_machines' => '二手机器',
        'd2u_machinery_used_machines_availability' => '现已上市',
        'd2u_machinery_used_machines_availible_from' => '从可用',
        'd2u_machinery_used_machines_config_error' => 'translation missing: d2u_machinery_used_machines_config_error',
        'd2u_machinery_used_machines_details' => '详细信息',
        'd2u_machinery_used_machines_external_url' => '详细信息',
        'd2u_machinery_used_machines_infos' => '其他信息',
        'd2u_machinery_used_machines_link_machine' => 'translation missing: d2u_machinery_used_machines_link_machine',
        'd2u_machinery_used_machines_location' => 'translation missing: d2u_machinery_used_machines_location',
        'd2u_machinery_used_machines_no_machines' => '目前有示范/二手设备可用。',
        'd2u_machinery_used_machines_offer_rent' => 'translation missing: d2u_machinery_used_machines_offer_rent',
        'd2u_machinery_used_machines_offers_rent' => 'translation missing: d2u_machinery_used_machines_offers_rent',
        'd2u_machinery_used_machines_offers_sale' => 'translation missing: d2u_machinery_used_machines_offers_sale',
        'd2u_machinery_used_machines_price' => 'translation missing: d2u_machinery_used_machines_price',
        'd2u_machinery_used_machines_price_on_request' => 'translation missing: d2u_machinery_used_machines_price_on_request',
        'd2u_machinery_used_machines_vat_excluded' => 'translation missing: d2u_machinery_used_machines_vat_excluded',
        'd2u_machinery_used_machines_vat_included' => 'translation missing: d2u_machinery_used_machines_vat_included',
        'd2u_machinery_used_machines_year_built' => '今年建成',
    ];

    private function getReplacementValue(string $key, int $clang_id): string
    {
        $lang_replacement = rex_config::get('d2u_machinery', 'lang_replacement_'. $clang_id, '');

        if ('chinese' === $lang_replacement && isset($this->replacements_chinese[$key])) {
            return $this->replacements_chinese[$key];
        }
        if ('dutch' === $lang_replacement && isset($this->replacements_dutch[$key])) {
            return $this->replacements_dutch[$key];
        }
        if ('french' === $lang_replacement && isset($this->replacements_french[$key])) {
            return $this->replacements_french[$key];
        }
        if ('german' === $lang_replacement && isset($this->replacements_german[$key])) {
            return $this->replacements_german[$key];
        }
        if ('portuguese' === $lang_replacement && isset($this->replacements_portuguese[$key])) {
            return $this->replacements_portuguese[$key];
        }
        if ('russian' === $lang_replacement && isset($this->replacements_russian[$key])) {
            return $this->replacements_russian[$key];
        }
        if ('spanish' === $lang_replacement && isset($this->replacements_spanish[$key])) {
            return $this->replacements_spanish[$key];
        }

        return $this->replacements_english[$key];
    }

    /**
     * @param array<int,string> $keys
     */
    /**
     * Factory method.
    * @return LangHelper Object
     */
    public static function factory()
    {
        return new self();
    }

    /**
     * Installs the replacement table for this addon.
     */
    public function install(): void
    {
        $overwrite = 'true' === rex_config::get('d2u_machinery', 'lang_wildcard_overwrite', false);
        foreach ($this->replacements_english as $key => $value) {
            unset($value);
            foreach (rex_clang::getAllIds() as $clang_id) {
                parent::saveValue($key, $this->getReplacementValue($key, $clang_id), $clang_id, $overwrite);
            }
        }
    }

    public function uninstall($clang_id = 0): void
    {
        parent::uninstall($clang_id);
    }
}
